import { PhotoData } from "@/lib/photo";

const data: PhotoData = {
  title: "キリギリス",
  date: "2022/3–",
  key: "kirigirisu",
  photos: [
    {
      src: "FNzBBdhaAAA6pni.webp",
      title: "",
      place: "ローソン 諏訪湖通り店",
      date: "",
      width: 1124,
      height: 2500,
    },
    {
      src: "FOoaiBKaAAYbSxi.webp",
      title: "",
      place: "熱海",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FOoaovpakAA9Fig.webp",
      title: "るるぶ",
      place: "箱根湯本",
      date: "",
      width: 2500,
      height: 2003,
    },
    {
      src: "FOqQ-90aIAIfgza.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1629,
    },
    {
      src: "FPPv3TQakAMfxzB.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FPZ-WPMagAA1Wya.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1872,
    },
    {
      src: "FPZgmFoaQAAeRhy.webp",
      title: "",
      place: "ラゾーナ川崎プラザ",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FPzQgvYVQAkFkd7.webp",
      title: "",
      place: "筑波大学 春日エリア",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FQbtSw3aIAAHPR0.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FRhJ3ZLVgAAhq4Q.webp",
      title: "",
      place: "",
      date: "",
      width: 1875,
      height: 2500,
    },
    {
      src: "FRhKAEVVUAEmW6N.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FRhKHOMUcAAhI4r.webp",
      title: "",
      place: "",
      date: "",
      width: 1875,
      height: 2500,
    },
    {
      src: "FRhKM2bVgAsMM6x.webp",
      title: "",
      place: "ヨークベニマルつくば竹園店",
      date: "",
      width: 768,
      height: 1024,
    },
    {
      src: "FTLiiSmaQAAha4L.webp",
      title: "",
      place: "トナリエつくばスクエア",
      date: "",
      width: 1875,
      height: 2500,
    },
    {
      src: "FTLipToaAAE9EaE.webp",
      title: "",
      place: "まめぽっと",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FTLix2zaAAALrIq.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1635,
    },
    {
      src: "FTm1PpdaQAAw5Ef.webp",
      title: "",
      place: "スシロー",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FTsrH_EaAAIdf_a.webp",
      title: "",
      place: "",
      date: "",
      width: 1875,
      height: 2500,
    },
    {
      src: "FTsrd2RakAEMoPY.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FU-VAReacAAVwr5.webp",
      title: "",
      place: "",
      date: "",
      width: 1496,
      height: 472,
    },
    {
      src: "FUFPtKKaMAEAYip.webp",
      title: "広報誌「Campus」",
      place: "筑波大学",
      date: "",
      width: 2500,
      height: 1605,
    },
    {
      src: "FUHm2HyaUAARlXC.webp",
      title: "",
      place: "",
      date: "",
      width: 1388,
      height: 662,
    },
    {
      src: "FV-9az_acAAcUk_.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FVbs44aaUAEnRz5.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FVdbyxuakAMRtNn.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1666,
    },
    {
      src: "FWZxtxMUIAAqokL.webp",
      title: "",
      place: "",
      date: "",
      width: 1462,
      height: 468,
    },
    {
      src: "FWlG_enaUAEE4kT.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FWlHFnkakAAesYW.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1709,
    },
    {
      src: "FWlIS5DaIAA1CLe.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1549,
    },
    {
      src: "FWun1XTaUAATwsT.webp",
      title: "",
      place: "アトレ川崎",
      date: "",
      width: 1875,
      height: 2500,
    },
    {
      src: "FWun4RuaIAASPK2.webp",
      title: "",
      place: "アトレ川崎",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FWvLhbJaQAAq6CP.webp",
      title: "",
      place: "",
      date: "",
      width: 1618,
      height: 2500,
    },
    {
      src: "FWvLl5sakAA6NM4.webp",
      title: "",
      place: "",
      date: "",
      width: 1875,
      height: 2500,
    },
    {
      src: "FWwPRE_aMAAZH1W.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FXDx7XfaIAAJwQJ.webp",
      title: "",
      place: "",
      date: "",
      width: 1875,
      height: 2500,
    },
    {
      src: "FXDx_ZjaIAE9Kq8.webp",
      title: "",
      place: "カルディコーヒーファーム イーアスつくば店",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FXDx_ZjaUAIxeAx.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FXDxzsrakAAqq12.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FXDyH5QaUAELqWH.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1882,
    },
    {
      src: "FXpNiWdaIAAca0I.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FXpNrTcaAAEXsJK.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FXtgONjaUAIcdM0.webp",
      title: "",
      place: "セブンイレブン 鬼怒川立岩店",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FYzeFTAaQAA5Kkm.webp",
      title: "",
      place: "めんたいパーク大洗",
      date: "",
      width: 2500,
      height: 1619,
    },
    {
      src: "FZFHG10aAAANTMK.webp",
      title: "",
      place: "",
      date: "",
      width: 828,
      height: 743,
    },
    {
      src: "FZFHLcHaIAAq4CT.webp",
      title: "",
      place: "大洗",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FZMpGgrakAAX7Lj.webp",
      title: "",
      place: "",
      date: "",
      width: 1875,
      height: 2500,
    },
    {
      src: "FZN9KiBacAAcy5I.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1935,
    },
    {
      src: "FZQBJb8aUAAwf7-.webp",
      title: "",
      place: "",
      date: "",
      width: 1875,
      height: 2500,
    },
    {
      src: "FZeH6IJacAEsqZx.webp",
      title: "",
      place: "",
      date: "",
      width: 1875,
      height: 2500,
    },
    {
      src: "FaOBEncaIAANEID.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 2134,
    },
    {
      src: "FaOBJD_akAA-lrb.webp",
      title: "",
      place: "",
      date: "",
      width: 1875,
      height: 2500,
    },
    {
      src: "FabusF8aUAA2xLO.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1518,
    },
    {
      src: "FanzC2pacAAVxHq.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "Fc2sPKXaIAEU3wk.webp",
      title: "",
      place: "",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "FdljVeyaAAMkgKQ.webp",
      title: "",
      place: "",
      date: "",
      width: 2048,
      height: 1533,
    },
    {
      src: "Fe51sWiaUAAHfGU.webp",
      title: "",
      place: "",
      date: "",
      width: 1536,
      height: 2048,
    },
    {
      src: "Ff1RcpVagAAkFh1.webp",
      title: "",
      place: "ずんだ茶寮 仙台駅ずんだ小径店",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "Ff1RlxTaAAE98yG.webp",
      title: "",
      place: "秋田",
      date: "",
      width: 2048,
      height: 1216,
    },
    {
      src: "FfJXyhiaMAA4dPh.webp",
      title: "",
      place: "",
      date: "",
      width: 1536,
      height: 2048,
    },
    {
      src: "FfQza4SaEAAuwWI.webp",
      title: "",
      place: "",
      date: "",
      width: 1536,
      height: 2048,
    },
    {
      src: "FfQzhW3aEAAwxKG.webp",
      title: "",
      place: "",
      date: "",
      width: 1536,
      height: 2048,
    },
    {
      src: "FfQzmunacAAI6OB.webp",
      title: "ドラえもん人形焼",
      place: "東京ソラマチ",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "FfQzqd1aYAEumik.webp",
      title: "",
      place: "",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "FfwH0ftaEAE5ATy.webp",
      title: "",
      place: "",
      date: "",
      width: 2048,
      height: 1446,
    },
    {
      src: "FfwHpakaEAI2IRw.webp",
      title: "",
      place: "",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "FfwHuCIaEAMCOwM.webp",
      title: "",
      place: "",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "FfwIAP1aYAAoaQv.webp",
      title: "",
      place: "",
      date: "",
      width: 1024,
      height: 642,
    },
    {
      src: "FgS56dHakAAdpn2.webp",
      title: "",
      place: "トナリエクレオ",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "FgUQizzaUAAqKfF.webp",
      title: "",
      place: "",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "FkXC0asaUAAcXu7.webp",
      title: "",
      place: "",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "Fkmkw2KagAAJZbJ.webp",
      title: "",
      place: "",
      date: "",
      width: 1536,
      height: 2048,
    },
    {
      src: "Fn5t000acAAtChL.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "Fn5t7tyaMAEKI69.webp",
      title: "",
      place: "",
      date: "",
      width: 1875,
      height: 2500,
    },
    {
      src: "FqsC5bSacAARner.webp",
      title: "彼氏彼女至上主義",
      place: "神田駅前",
      date: "",
      width: 1536,
      height: 2048,
    },
    {
      src: "FrAxGhdaUAMGkZX.webp",
      title: "",
      place: "",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "FrBGMyxaYAA5g4f.webp",
      title: "",
      place: "",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "FrFEcPVaEAAkPox.webp",
      title: "",
      place: "",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "FrFEcPZaUAAtHVR.webp",
      title: "",
      place: "",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "FrFEcQTaQAYxzZu.webp",
      title: "",
      place: "倉敷ロフト",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "FrFEcQWaMAItkH3.webp",
      title: "",
      place: "",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "FrKtjG7agAobX0B.webp",
      title: "",
      place: "",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "FrKtjG9acAUue17.webp",
      title: "",
      place: "小豆島",
      date: "",
      width: 2048,
      height: 1536,
    },
    {
      src: "FrM_p9gaIAEid1b.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FrM_p9laUAAR9l0.webp",
      title: "",
      place: "ザグザグ 土庄店",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FrM_p9lakAAk_6W.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "Fs0-vi7acAIC8nc.webp",
      title: "",
      place: "",
      date: "",
      width: 1536,
      height: 2048,
    },
    {
      src: "FtXYcycaEAEksoI.webp",
      title: "",
      place: "",
      date: "",
      width: 828,
      height: 488,
    },
    {
      src: "FtwT5DbaUAAntgE.webp",
      title: "",
      place: "トナリエつくばスクエア",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FuU3kQPaIAADG23.webp",
      title: "",
      place: "",
      date: "",
      width: 2048,
      height: 1570,
    },
    {
      src: "FulS1I0aEAEKo0d.webp",
      title: "",
      place: "",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "FulS1IxakAARtJ-.webp",
      title: "新歓祭パンフレット",
      place: "筑波大学",
      date: "",
      width: 2500,
      height: 1875,
    },
  ],
};

export default data;
