import { PhotoData } from "@/lib/photo";

const data: PhotoData = {
  title: "キロロ",
  date: "2020–2022",
  key: "kiroro",
  photos: [
    {
      src: "0.webp",
      title: "",
      place: "京都府京都市",
      date: "",
      width: 2500,
      height: 1666,
    },
    {
      src: "1.webp",
      title: "ベットに潜るキロロ",
      place: "ホテル, 京都府京都市",
      date: "",
      width: 2500,
      height: 1875,
    },
    {
      src: "2.webp",
      title: "神戸とキロロ",
      place: "ハーバーランド, 兵庫県神戸市",
      date: "",
      width: 1848,
      height: 2500,
    },
    {
      src: "3.webp",
      title: "お月見キロロ",
      place: "近所の公園, 神奈川県川崎市",
      date: "",
      width: 1667,
      height: 2500,
    },
    {
      src: "4.webp",
      title: "江ノ島キロロ",
      place: "腰越海岸, 神奈川県藤沢市",
      date: "2021/9/17",
      width: 2500,
      height: 1667,
    },
    {
      src: "5.webp",
      title: "雲の上のキロロ",
      place: "航空機内",
      date: "",
      width: 1979,
      height: 2500,
    },
    {
      src: "6.webp",
      title: "お花とキロロ",
      place: "江の島サムエル・コッキング苑, 神奈川県鎌倉市",
      date: "2021",
      width: 2500,
      height: 1667,
    },
    {
      src: "7.webp",
      title: "誕生日ケーキをみつめるキロロ",
      place: "自宅",
      date: "2021/9/16",
      width: 1667,
      height: 2500,
    },
    {
      src: "8.webp",
      title: "カメラを構えるキロロ",
      place: "奥多摩, 東京都奥多摩町",
      date: "2021/8/24",
      width: 2048,
      height: 1364,
    },
    {
      src: "9.webp",
      title: "夜景とキロロ",
      place: "ヴェルニー公園, 神奈川県横須賀市",
      date: "",
      width: 1024,
      height: 683,
    },
    {
      src: "10.webp",
      title: "毛布に包まるキロロ",
      place: "春日宿舎, 茨城県つくば市",
      date: "2021",
      width: 1023,
      height: 689,
    },
    {
      src: "11.webp",
      title: "談話室に集うキロロ",
      place: "春日宿舎, 茨城県つくば市",
      date: "2021/6/30",
      width: 1536,
      height: 2048,
    },
    {
      src: "12.webp",
      title: "談話室に集うキロロ",
      place: "春日宿舎, 茨城県つくば市",
      date: "2021",
      width: 2048,
      height: 1536,
    },
    {
      src: "13.webp",
      title: "布を被るキロロ",
      place: "春日宿舎, 茨城県つくば市",
      date: "2021",
      width: 2048,
      height: 1536,
    },
    {
      src: "14.webp",
      title: "とかげと勉強するキロロ",
      place: "春日宿舎, 茨城県つくば市",
      date: "2021",
      width: 2048,
      height: 1536,
    },
    {
      src: "15.webp",
      title: "くつろぐキロロ",
      place: "自宅",
      date: "",
      width: 2500,
      height: 1667,
    },
    {
      src: "16.webp",
      title: "東京タワーとキロロ",
      place: "六本木ヒルズ 東京シティビュー, 東京都港区",
      date: "2022/5/8",
      width: 2500,
      height: 1667,
    },
    {
      src: "17.webp",
      title: "包丁を向けられるキロロ",
      place: "友人宅, 神奈川県川崎市",
      date: "2020/3",
      width: 1108,
      height: 1477,
    },
    {
      src: "18.webp",
      title: "持たれるキロロ",
      place: "筑波大学, 茨城県つくば市",
      date: "2022",
      width: 2500,
      height: 1667,
    },
    {
      src: "19.webp",
      title: "jsys 局ミに出るキロロ",
      place: "筑波大学, 茨城県つくば市",
      date: "2022",
      width: 2500,
      height: 1674,
    },
    {
      src: "20.webp",
      title: "ZONe とキロロ",
      place: "",
      date: "",
      width: 2500,
      height: 1622,
    },
    {
      src: "21.webp",
      title: "ひっぱりキロロ",
      place: "自宅",
      date: "",
      width: 1200,
      height: 900,
    },
    {
      src: "22.webp",
      title: "メディア創成のパンフレットを眺めるキロロ",
      place: "筑波大学, 茨城県つくば市",
      date: "2022/4",
      width: 1200,
      height: 900,
    },
    {
      src: "23.webp",
      title: "ベストジーニストキロロロ",
      place: "自宅",
      date: "",
      width: 987,
      height: 1200,
    },
    {
      src: "24.webp",
      title: "桜とキロロ",
      place: "",
      date: "",
      width: 1200,
      height: 800,
    },
    {
      src: "25.webp",
      title: "桜とキロロ",
      place: "千鳥ヶ淵, 東京都千代田区",
      date: "2022/3/28",
      width: 800,
      height: 1200,
    },
    {
      src: "26.webp",
      title: "風呂上がりキロロ",
      place: "秋保温泉, 宮城県仙台市",
      date: "2020/2",
      width: 2500,
      height: 1875,
    },
    {
      src: "27.webp",
      title: "旅館でくつろぐキロロ",
      place: "",
      date: "",
      width: 1200,
      height: 800,
    },
    {
      src: "28.webp",
      title: "彫刻にのるキロロ",
      place: "上諏訪, 長野県諏訪市",
      date: "2022/3",
      width: 1200,
      height: 800,
    },
    {
      src: "29.webp",
      title: "殺生石とキロロ",
      place: "那須湯本温泉, 栃木県那須塩原市",
      date: "2022/3",
      width: 2048,
      height: 1365,
    },
    {
      src: "30.webp",
      title: "はさまるキロロ",
      place: "栃木県那須塩原市",
      date: "2022/3",
      width: 2048,
      height: 1365,
    },
    {
      src: "31.webp",
      title: "殺生石とキロロ",
      place: "那須湯本温泉, 栃木県那須塩原市",
      date: "2022/3",
      width: 1667,
      height: 2500,
    },
    {
      src: "32.webp",
      title: "なのはなとキロロ",
      place: "三浦海岸, 神奈川県三浦市",
      date: "2022/3/5",
      width: 1200,
      height: 800,
    },
    {
      src: "33.webp",
      title: "桜とキロロ",
      place: "三浦海岸, 神奈川県三浦市",
      date: "2022/3/5",
      width: 2500,
      height: 1667,
    },
    {
      src: "34.webp",
      title: "サイゼリヤとキロロ",
      place: "サイゼリヤ 川崎モアーズ店, 神奈川県川崎市",
      date: "2022/3/2",
      width: 2500,
      height: 1667,
    },
    {
      src: "35.webp",
      title: "コロナに気を付けるキロロ",
      place: "自宅",
      date: "2020",
      width: 900,
      height: 1200,
    },
    {
      src: "36.webp",
      title: "佐世保にはさまるキロロ",
      place: "佐世保港, 長崎県佐世保市",
      date: "2022/2/22",
      width: 1200,
      height: 800,
    },
    {
      src: "37.webp",
      title: "博多らーめんにご満悦のキロロ",
      place: "博多らーめん ShinShin 天神本店, 福岡県博多市",
      date: "2022/2/23",
      width: 1200,
      height: 900,
    },
    {
      src: "38.webp",
      title: "学園祭実行委員会にいるキロロ",
      place: "筑波大学 学園祭実行委員会室, 茨城県つくば市",
      date: "",
      width: 2500,
      height: 1650,
    },
    {
      src: "39.webp",
      title: "雪に埋まるキロロ",
      place: "",
      date: "",
      width: 2500,
      height: 1635,
    },
    {
      src: "40.webp",
      title: "雪景色の中のキロロ",
      place: "",
      date: "",
      width: 2500,
      height: 1666,
    },
    {
      src: "41.webp",
      title: "ベンチに座るキロロ",
      place: "",
      date: "",
      width: 2500,
      height: 1666,
    },
    {
      src: "42.webp",
      title: "オランジーナを飲むキロロ",
      place: "自宅",
      date: "",
      width: 1200,
      height: 891,
    },
    {
      src: "43.webp",
      title: "親子水入らずの時間を過ごすキロロ",
      place: "",
      date: "",
      width: 1200,
      height: 800,
    },
    {
      src: "44.webp",
      title: "銀世界の公園とキロロ",
      place: "近所の公園, 神奈川県川崎市",
      date: "",
      width: 1200,
      height: 835,
    },
    {
      src: "45.webp",
      title: "柔和な日差しを受けるキロロ",
      place: "山口県山陽小野田市",
      date: "",
      width: 1200,
      height: 800,
    },
    {
      src: "46.webp",
      title: "モンスターエナジーを飲むキロロ",
      place: "山口県山陽小野田市",
      date: "",
      width: 2500,
      height: 1667,
    },
    {
      src: "47.webp",
      title: "こたつの中で丸くなるキロロ",
      place: "山口県山陽小野田市",
      date: "",
      width: 2500,
      height: 1831,
    },
    {
      src: "48.webp",
      title: "すやすやキロロ",
      place: "山口県山陽小野田市",
      date: "",
      width: 1200,
      height: 775,
    },
    {
      src: "49.webp",
      title: "年賀状に登場するキロロ",
      place: "",
      date: "2022/1/1",
      width: 1200,
      height: 811,
    },
    {
      src: "50.webp",
      title: "サンタ帽を被るキロロ",
      place: "ステーキのあさくま 鶴見店, 神奈川県横浜市",
      date: "2021",
      width: 1200,
      height: 800,
    },
    {
      src: "51.webp",
      title: "サンタ帽を被るあずきちゃん",
      place: "自宅",
      date: "2021",
      width: 1200,
      height: 800,
    },
    {
      src: "52.webp",
      title: "クリスマス気分のキロロ",
      place: "自宅",
      date: "",
      width: 1200,
      height: 900,
    },
    {
      src: "ajisai.webp",
      title: "あじさいと戯れるキロロ",
      place: "明月院, 神奈川県鎌倉市",
      date: "2022/6/5",
      width: 2500,
      height: 1666,
    },
    {
      src: "bay-quarter.webp",
      title: "電飾に紛れるキロロ",
      place: "横浜ベイクォーター, 神奈川県横浜市",
      date: "2022/8/18",
      width: 2500,
      height: 1666,
    },
    {
      src: "c101.webp",
      title: "コミックマーケットに参戦するキロロ",
      place: "東京ビッグサイト 東駐車場, 東京都江東区",
      date: "2022/12/30",
      width: 1536,
      height: 2048,
    },
    {
      src: "cheese-gyudon.webp",
      title: "チーズ牛丼を食べるキロロ",
      place: "筑波大学, 茨城県つくば市",
      date: "2021/11/7",
      width: 2500,
      height: 1875,
    },
    {
      src: "cojt.webp",
      title: "実験に参加するキロロ",
      place: "筑波大学, 茨城県つくば市",
      date: "2023/8/2",
      width: 2500,
      height: 1667,
    },
    {
      src: "dakishime.webp",
      title: "抱きしめられるキロロ",
      place: "",
      date: "202/5/25",
      width: 2500,
      height: 1667,
    },
    {
      src: "enoshima-candle.webp",
      title: "江ノ島で黄昏るキロロ",
      place: "江の島シーキャンドル, 神奈川県藤沢市",
      date: "2023/6/18",
      width: 2048,
      height: 1536,
    },
    {
      src: "expasa.webp",
      title: "談合坂にきたキロロ",
      place: "EXPASA 談合坂, 山梨県上野原市",
      date: "2022/9/4",
      width: 1536,
      height: 2048,
    },
    {
      src: "family.webp",
      title: "家族が増えたキロロ",
      place: "自宅",
      date: "",
      width: 2500,
      height: 1667,
    },
    {
      src: "ganen.webp",
      title: "岩塩を食べるキロロ",
      place: "",
      date: "2023/6/28",
      width: 2500,
      height: 1667,
    },
    {
      src: "good-design.webp",
      title: "グッドデザインになるキロロ",
      place: "東京ミッドタウン・デザインハブ, 東京都港区",
      date: "2021/11/15",
      width: 2500,
      height: 1875,
    },
    {
      src: "grabber.webp",
      title: "グラバーと並ぶキロロ",
      place: "グラバー園, 長崎県長崎市",
      date: "2022/2/21",
      width: 2500,
      height: 1742,
    },
    {
      src: "hatsuhinode.webp",
      title: "初日の出になるキロロ",
      place: "山口県山陽小野田市",
      date: "2022/1/1",
      width: 2500,
      height: 1875,
    },
    {
      src: "hiratsuka22.webp",
      title: "七夕飾りに紛れるキロロ",
      place: "湘南スターモール商店街, 神奈川県平塚市",
      date: "2022/7/9",
      width: 2500,
      height: 1666,
    },
    {
      src: "interview.webp",
      title: "インタビューを受けるキロロ",
      place: "筑波大学, 茨城県つくば市",
      date: "2022/9/15",
      width: 2048,
      height: 1497,
    },
    {
      src: "jsys22.webp",
      title: "学園祭の準備をするキロロ",
      place: "大学会館, 茨城県つくば市",
      date: "2022/9/15",
      width: 2048,
      height: 1364,
    },
    {
      src: "kagee.webp",
      title: "影絵になるキロロ",
      place: "春日宿舎, 茨城県つくば市",
      date: "2021/10/6",
      width: 2500,
      height: 2246,
    },
    {
      src: "kanayakou.webp",
      title: "海風を受けるキロロ",
      place: "金谷港, 千葉県富津市",
      date: "2022/8/19",
      width: 2500,
      height: 1667,
    },
    {
      src: "kasuga-koudou.webp",
      title: "講堂に座るキロロ",
      place: "筑波大学 春日講堂, 茨城県つくば市",
      date: "2022/7/4",
      width: 2500,
      height: 1667,
    },
    {
      src: "marunouchi0.webp",
      title: "丸の内で腰掛けるキロロ",
      place: "丸の内仲通り, 東京都千代田区",
      date: "2021/12/12",
      width: 2500,
      height: 1667,
    },
    {
      src: "marunouchi1.webp",
      title: "丸の内でドヤ顔をするキロロ",
      place: "丸の内仲通り, 東京都千代田区",
      date: "2021/12/12",
      width: 2500,
      height: 1667,
    },
    {
      src: "mitou.webp",
      title: "未踏の発表をするキロロ",
      place: "自宅",
      date: "2020/4",
      width: 2500,
      height: 1546,
    },
    {
      src: "otaru.webp",
      title: "小樽にきたキロロ",
      place: "小樽駅, 北海道小樽市",
      date: "2023/1/14",
      width: 2048,
      height: 1536,
    },
    {
      src: "pengin.webp",
      title: "ペンギンとシンパシーを感じるキロロ",
      place: "葛西臨海水族園, 東京都江戸川区",
      date: "2023/5/28",
      width: 1536,
      height: 2048,
    },
    {
      src: "projection.webp",
      title: "春にきたキロロ",
      place: "友人宅, 茨城県つくば市",
      date: "2022/2/11",
      width: 2500,
      height: 1666,
    },
    {
      src: "sohosai22.webp",
      title: "学園祭の準備期間のキロロ",
      place: "筑波大学 石の広場, 茨城県つくば市",
      date: "2022/11/9",
      width: 2048,
      height: 1366,
    },
    {
      src: "solid.webp",
      title: "あずきちゃんと過ごすキロロ",
      place: "ソリッドスクエア, 神奈川県川崎市",
      date: "202３/9/26",
      width: 2500,
      height: 1667,
    },
    {
      src: "torisen.webp",
      title: "とりせんで買い物をするキロロ",
      place: "とりせん 研究学園店, 茨城県つくば市",
      date: "2023/6/13",
      width: 1920,
      height: 1440,
    },
    {
      src: "toukyouwan-ferry.webp",
      title: "フェリーに揺られるキロロ",
      place: "東京湾フェリー",
      date: "2022/8/19",
      width: 1909,
      height: 2500,
    },
    {
      src: "tsukuba-center.webp",
      title: "オタマトーンの目になるキロロ",
      place: "つくばセンター広場, 茨城県つくば市",
      date: "2022/11/2",
      width: 2048,
      height: 1536,
    },
    {
      src: "ueda.webp",
      title: "公園でひと休みするキロロ",
      place: "長野県上田市",
      date: "2022/10/1",
      width: 2500,
      height: 1667,
    },
    {
      src: "umeshu.webp",
      title: "梅酒を飲むキロロ",
      place: "友人宅, 茨城県つくば市",
      date: "2023/6/28",
      width: 1875,
      height: 2500,
    },
    {
      src: "wanokuni.webp",
      title: "新しいらーめん屋にきたキロロ",
      place: "和の国 KAGUYA RAMEN, 茨城県つくば市",
      date: "2023/4/18",
      width: 1536,
      height: 2048,
    },
    {
      src: "ysfh23.webp",
      title: "オブジェにはさまるキロロ",
      place: "横浜サイエンスフロンティア高校, 神奈川県横浜市",
      date: "2023/6/24",
      width: 1666,
      height: 2500,
    },
  ],
};

export default data;
