export const ramenInfos = [
  { title: "いっとく", days: "月火水木金土日" },
  { title: "七福軒", days: "月火水木金土日" },
  { title: "油虎", days: "月火水木金土日" },
  { title: "清六家", days: "月火水木金土日" },
  { title: "喜元門", days: "月火水木金土日" },
  { title: "一休", days: "月火水木金土日" },
  { title: "洋介", days: "月火水木金土日" },
  { title: "甲殻堂", days: "月火水木金土日" },
  { title: "真壁屋", days: "月火水木金土日" },
  { title: "活龍", days: "月火水木金土日" },
  { title: "ごう家", days: "月火水木金土日" },
  { title: "俺の生きる道", days: "月火水木金土日" },
  { title: "芛堂寺", days: "月火水木金土日" },
  { title: "むじゃき", days: "月火水木金土日" },
  { title: "青葉", days: "月火水木金土日" },
  { title: "ICHI", days: "月火水木金土日" },
  { title: "丸源", days: "月火水木金土日" },
  { title: "龍郎", days: "月火水木金土日（不定休）" },
  { title: "イチカワ", days: "月火水木金土" },
  { title: "大元", days: "月火水木金土" },
  { title: "がむしゃ", days: "月火水木金土" },
  { title: "ららららーめんや", days: "月火水木金土" },
  { title: "蒼", days: "月火　木金土日" },
  { title: "丸長", days: "月火　木金土日" },
  { title: "飯村製作所", days: "月火　木金土日" },
  { title: "鬼屋", days: "月　水木金土日" },
  { title: "鶏々", days: "月　水木金土日" },
  { title: "銀の豚", days: "月　水木金土日" },
  { title: "とみよし", days: "月　水木金土日" },
  { title: "コンタス", days: "月　水木金土日" },
  { title: "必道", days: "月火水　金土日" },
  { title: "鬼者語", days: "月火水　金土日" },
  { title: "とどろき", days: "　火水　金土日" },
  { title: "盛清六", days: "　火水木金土日" },
  { title: "がく", days: "　火水木金土日" },
  { title: "異国龍", days: "　火水木金土日" },
  { title: "小五郎", days: "　火水木金土日" },
  { title: "はりけん", days: "　火水木金土日" },
  { title: "JUNCHAN", days: "　火水木金土日" },
  { title: "秀彬", days: "　火水木金土日" },
  { title: "千里", days: "　火水木金土日" },
];
